apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: default
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
spec:
  rules:
  - host: drone.longban.site
    http:
      paths:
      - backend:
          serviceName: drone
          servicePort: 80
  - host: gitlab.longban.site
    http:
      paths:
      - backend:
          serviceName: gitlab
          servicePort: 80
  - host: redmine.longban.site
    http:
      paths:
      - backend:
          serviceName: zentao
          servicePort: 80
  tls:
  - hosts:
    - drone.longban.site
    secretName: drone
  - hosts:
    - gitlab.longban.site
    secretName: gitlab
  - hosts:
    - redmine.longban.site
    secretName: redmine
