FROM openresty/openresty:1.13.6.1-centos

MAINTAINER monkey <bufan@szxintom.com>

RUN curl --silent --location https://rpm.nodesource.com/setup_8.x | bash - \
    && yum install -y gcc-c++ make \
    && yum install -y nodejs
