version: '2'
networks:
  longban:
    driver: bridge
    ipam:
      config:
      - subnet: 10.2.0.0/16
        gateway: 10.2.1.1
services:
  postgresql:
    image: sameersbn/postgresql:9.6-2
    environment:
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production
    volumes:
    - /data/docker/redmine/postgresql:/var/lib/postgresql
    networks:
      longban:
        ipv4_address: 10.2.0.2

  redmine:
    image: sameersbn/redmine:3.4.2
    depends_on:
    - postgresql
    environment:
    - TZ=Asia/Shanghai
    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production
    
    - REDMINE_PORT=443
    - REDMINE_HTTPS=true
    - REDMINE_RELATIVE_URL_ROOT=
    - REDMINE_SECRET_TOKEN=
    
    - REDMINE_SUDO_MODE_ENABLED=false
    - REDMINE_SUDO_MODE_TIMEOUT=15
    
    - REDMINE_CONCURRENT_UPLOADS=2
    
    - REDMINE_BACKUP_SCHEDULE=
    - REDMINE_BACKUP_EXPIRY=
    - REDMINE_BACKUP_TIME=
    
    - SMTP_ENABLED=true
    - SMTP_METHOD=smtp
    - SMTP_DOMAIN=smtp.163.com
    - SMTP_HOST=smtp.163.com
    - SMTP_PORT=465
    - SMTP_USER=13249629530@163.com
    - SMTP_PASS=
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:plain
    - SMTP_TLS=true
    
    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_INTERVAL=30
    volumes:
    - /data/docker/redmine/redmine:/home/redmine/data
    networks:
      longban:
        ipv4_address: 10.2.0.1

