apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: kube-system
  labels:
    k8s-app: logstash
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Logstash"
spec:
  ports:
  - port: 5959
    targetPort: logstash-udp
    name: logstash-udp
    protocol: UDP
  - port: 5959
    targetPort: logstash-tcp
    name: logstash-tcp
    protocol: TCP
  selector:
    k8s-app: logstash
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: kube-system
  labels:
    k8s-app: logstash
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      k8s-app: logstash
  replicas: 2
  template:
    metadata:
      labels:
        k8s-app: logstash
        kubernetes.io/cluster-service: "true"
      annotations: {version/config: 20180427-05}
    spec:
      containers:
      - name: logstash
        image: harbor.longban.site/k8s/logstash:5.1.1
        volumeMounts:
        - name: logstash-conf
          mountPath: /config-dir/
        command: ["logstash", "-f", "/config-dir/logstash.conf"]
        ports:
        - name: logstash-tcp
          containerPort: 5959
          protocol: TCP
        - name: logstash-udp
          containerPort: 5959
          protocol: UDP
      terminationGracePeriodSeconds: 30
      volumes:
      - name: logstash-conf
        configMap:
          name: logstash-config
          items:
          - key: logstash.conf
            path: logstash.conf

