---
kind: Service
apiVersion: v1
metadata:
  name: gitlab
spec:
  selector:
    app: gitlab
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
    name: http
  - protocol: TCP
    port: 22
    nodePort: 10022
    targetPort: ssh
    name: ssh
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  replicas: 1
  selector:
    matchLabels: {app: gitlab}
  template:
    metadata:
      labels: {app: gitlab}
    spec:
      nodeSelector:
        kubernetes.io/hostname: 192.168.0.118
      volumes:
      - name: gitlab-redis
        hostPath:
          path: "/data/docker/gitlab/redis"
          type: Directory
      - name: gitlab-postgresql
        hostPath:
          path: "/data/docker/gitlab/postgresql"
          type: Directory
      - name: gitlab
        hostPath:
          path: "/data/docker/gitlab/gitlab"
          type: Directory
      containers:
      - image: sameersbn/redis:latest
        name: redis
        volumeMounts:
        - name: gitlab-redis
          mountPath: /var/lib/redis
      - image: sameersbn/postgresql:9.6-2
        name: postgresql
        volumeMounts:
        - name: gitlab-postgresql
          mountPath: /var/lib/postgresql
        env:
        - {name: "DB_USER", value: "gitlab"}
        - {name: "DB_PASS", value: "password"}
        - {name: "DB_NAME", value: "gitlabhq_production"}
        - {name: "DB_EXTENSION", value: "pg_trgm"}
      - image: sameersbn/gitlab:10.1.1
        name: gitlab
        volumeMounts:
        - name: gitlab
          mountPath: /home/git/data
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 22
          name: ssh
          protocol: TCP
        env:
        - {name: "DEBUG", value: "false"}
     
        - {name: "DB_ADAPTER", value: "postgresql"}
        - {name: "DB_HOST", value: "localhost"}
        - {name: "DB_PORT", value: "5432"}
        - {name: "DB_USER", value: "gitlab"}
        - {name: "DB_PASS", value: "password"}
        - {name: "DB_NAME", value: "gitlabhq_production"}
     
        - {name: "REDIS_HOST", value: "localhost"}
        - {name: "REDIS_PORT", value: "6379"}
     
        - {name: "TZ", value: "Asia/Kolkata"}
        - {name: "GITLAB_TIMEZONE", value: "Kolkata"}
     
        - {name: "GITLAB_HTTPS", value: "true"}
        - {name: "SSL_SELF_SIGNED", value: "false"}
     
        - {name: "GITLAB_HOST", value: "gitlab.longban.site"}
        - {name: "GITLAB_PORT", value: "443"}
        - {name: "GITLAB_SSH_PORT", value: "10022"}
        - {name: "GITLAB_RELATIVE_URL_ROOT", value: ""}
        - {name: "GITLAB_SECRETS_DB_KEY_BASE", value: "long-and-random-alphanumeric-string"}
        - {name: "GITLAB_SECRETS_SECRET_KEY_BASE", value: "long-and-random-alphanumeric-string"}
        - {name: "GITLAB_SECRETS_OTP_KEY_BASE", value: "long-and-random-alphanumeric-string"}
     
        - {name: "GITLAB_NOTIFY_ON_BROKEN_BUILDS", value: "true"}
        - {name: "GITLAB_NOTIFY_PUSHER", value: "false"}
     
        - {name: "GITLAB_BACKUP_SCHEDULE", value: "daily"}
        - {name: "GITLAB_BACKUP_TIME", value: "01:00"}
     
        - {name: "SMTP_ENABLED", value: "false"}
        - {name: "SMTP_DOMAIN", value: "smtp.exmail.qq.com"}
        - {name: "SMTP_HOST", value: "smtp.exmail.qq.com"}
        - {name: "SMTP_PORT", value: "465"}
        - {name: "SMTP_USER", value: "bufan@szxintom.com"}
        - {name: "SMTP_PASS", value: "Xin1101"}
        - {name: "SMTP_STARTTLS", value: "true"}
        - {name: "SMTP_AUTHENTICATION", value: "login"}
     
        - {name: "OAUTH_ENABLED", value: "true"}
        - {name: "OAUTH_AUTO_SIGN_IN_WITH_PROVIDER", value: ""}
        - {name: "OAUTH_ALLOW_SSO", value: ""}
        - {name: "OAUTH_BLOCK_AUTO_CREATED_USERS", value: "true"}
        - {name: "OAUTH_AUTO_LINK_LDAP_USER", value: "false"}
        - {name: "OAUTH_AUTO_LINK_SAML_USER", value: "false"}
        - {name: "OAUTH_EXTERNAL_PROVIDERS", value: ""}
     
        - {name: "OAUTH_CAS3_LABEL", value: "cas3"}
        - {name: "OAUTH_CAS3_SERVER", value: ""}
        - {name: "OAUTH_CAS3_DISABLE_SSL_VERIFICATION", value: "false"}
        - {name: "OAUTH_CAS3_LOGIN_URL", value: "/cas/login"}
        - {name: "OAUTH_CAS3_VALIDATE_URL", value: "/cas/p3/serviceValidate"}
        - {name: "OAUTH_CAS3_LOGOUT_URL", value: "/cas/logout"}
     
        - {name: "OAUTH_GOOGLE_API_KEY", value: ""}
        - {name: "OAUTH_GOOGLE_APP_SECRET", value: ""}
        - {name: "OAUTH_GOOGLE_RESTRICT_DOMAIN", value: ""}
        - {name: "OAUTH_SAML_LABEL", value: "Our SAML Provider"}
        - {name: "OAUTH_SAML_NAME_IDENTIFIER_FORMAT", value: ":urnoasis:names:tc:SAML:2.0:nameid-format:transient"}
    
